version: "3.5"

services:
  api:
    image: ingshtrom/playlister:local
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        monitor: 1m
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.4"
          memory: 256M
    depends_on:
      - db
    ports:
      - 3001:3001
    command: [ "pm2-runtime", "./bin/www" ]
    env_file:
      - /opt/api.env
    networks:
      - backend

  db:
    image: mysql:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.6"
          memory: 512M
    env_file:
      - /opt/db.env
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
