version: "3.5"

services:
  process_media:
    build:
      context: ./node
      dockerfile: process_media.Dockerfile
    command: [ "pm2-dev", "./bin/process_media.js" ]
    env_file:
      - ./node/.env
    links:
      - db
    volumes:
      - ./node:/opt/app:consistent
      - file_process:/data/playlister-upload:consistent

  api:
    build: ./node
    ports:
      - 3001:3001
    command: [ "pm2-dev", "./bin/www" ]
    env_file:
      - ./node/.env
    links:
      - db
    volumes:
      - ./node:/opt/app:consistent
      - file_process:/data/playlister-upload:consistent

  web:
    build: ./react
    ports:
      - 3000:3000
    command: [ "node", "scripts/start.js" ]
    volumes:
      - ./react:/opt/app:consistent
    links:
      - api

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=playlister
    ports:
      - 3306:3306

volumes:
  file_process:
    driver: local

