version: "3.5"

services:
  process_media:
    image: ingshtrom/playlister-process-media:local
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        monitor: 15s
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    depends_on:
      - db
    command: [ "pm2-runtime", "./bin/process_media.js" ]
    volumes:
      - file_process:/data/playlister-upload:consistent
    env_file:
      - /opt/api.env
    networks:
      - backend

  api:
    image: ingshtrom/playlister:local
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        monitor: 1m
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    depends_on:
      - db
    ports:
      - 3001:3001
    command: [ "pm2-runtime", "./bin/www" ]
    env_file:
      - /opt/api.env
    volumes:
      - file_process:/data/playlister-upload:consistent
    networks:
      - backend

  db:
    image: mysql:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.6"
          memory: 512M
    env_file:
      - /opt/db.env
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  file_process:
